//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int FileID { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public string FileType { get; set; }
        public Nullable<int> FileTypeID { get; set; }
    }
}
