//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int ID { get; set; }
        public int EmployeePK { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
