//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.PriceQuotes = new HashSet<PriceQuotes>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int CustomerPK { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public bool isDone { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceQuotes> PriceQuotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
        public int CustomerID { get; set; }
    }
}
