//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Employee_Activity
    {
        public int TaskID { get; set; }
        public int EmployeePK { get; set; }
        public int ActivityID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
